trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
  # Sample command to test echo
  - script: echo This is a build pipeline using Azure-pipelines
  # This is a sample command to test mkdir
  - script: mkdir sampledir

  # Actual script needed for you.
  - script: |
        ls -ltr 
        az login --service-principal --username "3d587273-dcac-47f1-b714-72f244c67c52"  --password "8ec3a20c-e55e-4341-abec-28d57eab3be1" --tenant "59b2865a-7fb8-4ccb-ab68-72cbca88fc48"
        # Update for your admin password
        AdminPassword=MLK123ATL!!ffD$
        rgName=myResourceGroup4
        locName=westeurope
        vnetName=myVnet4
        subnetName=mySubnet4
        publicIP=myPublicIP4
        nsgName=myNetworkSecurityGroup4
        nicName=myNic4
        vmName=myVM4
        userName=clouduser

        az group create --name $rgName --location $locName  --output table
        az network vnet create --resource-group $rgName --name $vnetName --subnet-name $subnetName  --output table
        az network public-ip create --resource-group $rgName --name $publicIP  --output table

        az network nsg create --resource-group $rgName --name $nsgName  --output table

        az network nic create \
           --resource-group $rgName \
           --name $nicName \
           --vnet-name $vnetName \
           --subnet $subnetName \
           --network-security-group $nsgName \
           --public-ip-address $publicIP \
           --output table

        az vm create \
           --resource-group $rgName \
           --name $vmName \
           --location $locName \
           --image OpenLogic:CentOS-CI:7-CI:latest \
           --admin-username $userName \
           --admin-password $AdminPassword \
           --generate-ssh-keys \
           --output table
           
        az vm run-command invoke -g $rgName -n $vmName --command-id RunShellScript --scripts "sudo touch /tmp/file1.txt && sudo curl -fsSL https://get.docker.com/ | sh"  --output table
        # az vm open-port --port 3389 --resource-group myResourceGroup --name myVM
