trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
  # Sample command to test echo
  - script: echo This is a build pipeline using Azure-pipelines
  # This is a sample command to test mkdir
  - script: mkdir sampledir

  # Actual script needed for you.
  - script: |
        ls -ltr 
        az login --service-principal --username "3d587273-dcac-47f1-b714-72f244c67c52"  --password "8ec3a20c-e55e-4341-abec-28d57eab3be1" --tenant "59b2865a-7fb8-4ccb-ab68-72cbca88fc48"
        # Update for your admin password
        AdminPassword=MLK123ATL!!ffD$
        az group create --name myResourceGroup3 --location westeurope
        az network vnet create --resource-group myResourceGroup3 --name myVnet3 --subnet-name mySubnet3
        az network public-ip create --resource-group myResourceGroup3 --name myPublicIP3

        az network nsg create --resource-group myResourceGroup3 --name myNetworkSecurityGroup3

        az network nic create \
           --resource-group myResourceGroup3 \
           --name myNic3 \
           --vnet-name myVnet3 \
           --subnet mySubnet3 \
           --network-security-group myNetworkSecurityGroup3 \
           --public-ip-address myPublicIP3


        #  az vm create \
        #   --resource-group myResourceGroup \
        #   --name myVM \
        #   --location westeurope \
        #   --nics myNic \
        #   --image win2016datacenter \
        #   --admin-username azureuser \
        #   --admin-password $AdminPassword
        az vm create \
           --resource-group myResourceGroup3 \
           --name myVM1 \
           --location westeurope \
           --image CentOS \
           --admin-username azureuser \
           --admin-password $AdminPassword \
           --generate-ssh-keys
           
        az vm run-command invoke -g myResourceGroup3 -n myVm3 --command-id RunShellScript --scripts "sudo yum update && sudo touch /tmp/file1.txt && curl -fsSL https://get.docker.com/ | sh"
        # az vm open-port --port 3389 --resource-group myResourceGroup --name myVM
