trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
  # Sample command to test echo
  - script: echo This is a build pipeline using Azure-pipelines
  # This is a sample command to test mkdir
  - script: mkdir sampledir

  # Actual script needed for you.
  - script: |
        ls -ltr 
        az login --service-principal --username "3d587273-dcac-47f1-b714-72f244c67c52"  --password "8ec3a20c-e55e-4341-abec-28d57eab3be1" --tenant "59b2865a-7fb8-4ccb-ab68-72cbca88fc48"
        # Update for your admin password
        AdminPassword=MLK123ATL!!ffD$
        az group create --name myResourceGroup --location westeurope
        az network vnet create --resource-group myResourceGroup --name myVnet --subnet-name mySubnet
        az network public-ip create --resource-group myResourceGroup --name myPublicIP

        az network nsg create --resource-group myResourceGroup --name myNetworkSecurityGroup

        az network nic create \
           --resource-group myResourceGroup \
           --name myNic \
           --vnet-name myVnet \
           --subnet mySubnet \
           --network-security-group myNetworkSecurityGroup \
           --public-ip-address myPublicIP


        az vm create \
           --resource-group myResourceGroup \
           --name myVM \
           --location westeurope \
           --nics myNic \
           --image win2016datacenter \
           --admin-username azureuser \
           --admin-password $AdminPassword

        az vm open-port --port 3389 --resource-group myResourceGroup --name myVM
